const ProductItem = [
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: false,
        onSale: true,
        saleRate: 50,
        rate: 1.5,
        key: 1,
        id: 1
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: true,
        onSale: false,
        saleRate: 0,
        rate: 4.5,
        key: 2,
        id: 2
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: true,
        onSale: true,
        saleRate: 10,
        rate: 4,
        key: 3,
        id: 3
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: true,
        onSale: false,
        saleRate: 0,
        rate: 3,
        key: 4,
        id: 4
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: true,
        onSale: true,
        saleRate: 20,
        rate: 5,
        key: 5,
        id: 5
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: true,
        onSale: false,
        saleRate: 0,
        rate: 4.5,
        key: 6,
        id: 6
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: false,
        onSale: false,
        saleRate: 0,
        rate: 2.5,
        key: 7,
        id: 7
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: true,
        onSale: false,
        saleRate: 50,
        rate: 3.5,
        key: 8,
        id: 8
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: true,
        onSale: false,
        saleRate: 0,
        rate: 3,
        key: 9,
        id: 9
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: true,
        onSale: true,
        saleRate: 20,
        rate: 5,
        key: 10,
        id: 10
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: true,
        onSale: false,
        saleRate: 0,
        rate: 4.5,
        key: 11,
        id: 11
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: false,
        onSale: true,
        saleRate: 20,
        rate: 2.5,
        key: 12,
        id: 12
    },
    {
        imgUrl: "https://i.pinimg.com/236x/ef/f6/77/eff677fe6e1a71db2b8912a7ff5672fc.jpg",
        imgAlt: "colorful-necklace",
        productName: "Colorful Rainbow Necklace",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit..",
        price: 10,
        freeShipping: true,
        onSale: true,
        saleRate: 10,
        rate: 3,
        key: 13,
        id: 13
    }
]

export default ProductItem;